---
- name: Deploy CoreDNS to fix cluster DNS
  hosts: rke2_masters[0]
  gather_facts: false
  become: true

  tasks:
    - name: Check if CoreDNS is already deployed
      ansible.builtin.command: kubectl get deployment -n kube-system coredns
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: coredns_check
      failed_when: false
      changed_when: false

    - name: Deploy CoreDNS
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/coredns/deployment/master/kubernetes/coredns.yaml.sed
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: coredns_check.rc != 0

    - name: Create CoreDNS ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: coredns
            namespace: kube-system
          data:
            Corefile: |
              .:53 {
                  errors
                  health {
                      lameduck 5s
                  }
                  ready
                  kubernetes cluster.local in-addr.arpa ip6.arpa {
                      pods insecure
                      fallthrough in-addr.arpa ip6.arpa
                      ttl 30
                  }
                  prometheus :9153
                  forward . /etc/resolv.conf {
                      max_concurrent 1000
                  }
                  cache 30
                  loop
                  reload
                  loadbalance
              }
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create CoreDNS Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kube-dns
            namespace: kube-system
            labels:
              k8s-app: kube-dns
              kubernetes.io/cluster-service: "true"
              kubernetes.io/name: CoreDNS
          spec:
            selector:
              k8s-app: kube-dns
            clusterIP: 10.43.0.10
            ports:
              - name: dns
                port: 53
                protocol: UDP
              - name: dns-tcp
                port: 53
                protocol: TCP
              - name: metrics
                port: 9153
                protocol: TCP
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create CoreDNS Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: coredns
            namespace: kube-system
            labels:
              k8s-app: kube-dns
              kubernetes.io/name: CoreDNS
          spec:
            replicas: 2
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxUnavailable: 1
            selector:
              matchLabels:
                k8s-app: kube-dns
            template:
              metadata:
                labels:
                  k8s-app: kube-dns
              spec:
                priorityClassName: system-cluster-critical
                serviceAccountName: coredns
                tolerations:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                    effect: NoSchedule
                  - key: CriticalAddonsOnly
                    operator: Exists
                nodeSelector:
                  kubernetes.io/os: linux
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          labelSelector:
                            matchExpressions:
                              - key: k8s-app
                                operator: In
                                values: ["kube-dns"]
                          topologyKey: kubernetes.io/hostname
                containers:
                  - name: coredns
                    image: coredns/coredns:1.11.1
                    imagePullPolicy: IfNotPresent
                    resources:
                      limits:
                        memory: 170Mi
                      requests:
                        cpu: 100m
                        memory: 70Mi
                    args: ["-conf", "/etc/coredns/Corefile"]
                    volumeMounts:
                      - name: config-volume
                        mountPath: /etc/coredns
                        readOnly: true
                    ports:
                      - containerPort: 53
                        name: dns
                        protocol: UDP
                      - containerPort: 53
                        name: dns-tcp
                        protocol: TCP
                      - containerPort: 9153
                        name: metrics
                        protocol: TCP
                    livenessProbe:
                      httpGet:
                        path: /health
                        port: 8080
                        scheme: HTTP
                      initialDelaySeconds: 60
                      timeoutSeconds: 5
                      successThreshold: 1
                      failureThreshold: 5
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: 8181
                        scheme: HTTP
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        add:
                          - NET_BIND_SERVICE
                        drop:
                          - all
                      readOnlyRootFilesystem: true
                dnsPolicy: Default
                volumes:
                  - name: config-volume
                    configMap:
                      name: coredns
                      items:
                        - key: Corefile
                          path: Corefile
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create CoreDNS ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: coredns
            namespace: kube-system
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create CoreDNS ClusterRole
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: system:coredns
          rules:
            - apiGroups: [""]
              resources: ["endpoints", "services", "pods", "namespaces"]
              verbs: ["list", "watch"]
            - apiGroups: ["discovery.k8s.io"]
              resources: ["endpointslices"]
              verbs: ["list", "watch"]
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create CoreDNS ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: system:coredns
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:coredns
          subjects:
            - kind: ServiceAccount
              name: coredns
              namespace: kube-system
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for CoreDNS to be ready
      ansible.builtin.command: >
        kubectl wait --for=condition=ready pod
        -l k8s-app=kube-dns
        -n kube-system
        --timeout=300s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Verify DNS is working
      ansible.builtin.command: >
        kubectl run -it --rm debug --image=busybox --restart=Never -- nslookup kubernetes.default
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: dns_test
      failed_when: false
      changed_when: false

    - name: Display DNS test result
      ansible.builtin.debug:
        msg: "{{ dns_test.stdout_lines }}"
